#ifndef DAT_H
#define DAT_H

enum DAT_SUBTYPE {
    DAT_UNKNOWN_00 /* 0x00 */,
    DAT_TYPE_0_PLAYER_START_POSITION /* 0x01 */,
    DAT_TYPE_0_RESTART_POSITION /* 0x02 Mostly used by players, but used for Moff Seerdon too */,
    DAT_TYPE_3_03 /* 0x03 "regular" spline type */,
    DAT_TYPE_6_HIGH_LOD_BOX /* 0x04 Name is speculative */,
    DAT_TYPE_6_LOW_LOD_BOX /* 0x05 Name is speculative */,
    DAT_TYPE_0_HANGAR_SUBTYPE0 /* 0x06 Only used in the hangar, mostly in reference to the player craft */,
    DAT_TYPE_0_HANGAR_SUBTYPE1 /* 0x07 Used in the hangar, bridge, and logo scenes, purpose unknown */,
    DAT_TYPE_3_08 /* 0x08 Another spline type, only used in the hangar and the logo scenes */,
    DAT_TYPE_2_09 /* 0x09 */,
    DAT_UNKNOWN_0A /* 0x0A */,
    DAT_UNKNOWN_0B /* 0x0B */,
    DAT_TYPE_0_TIE_FIGHTER /* 0x0C */,
    DAT_TYPE_0_GUN_TURRET /* 0x0D */,
    DAT_TYPE_0_PROBE_DROID /* 0x0E */,
    DAT_TYPE_0_ATAT /* 0x0F */,
    DAT_TYPE_6_MUSIC_RNG /* 0x10 */,
    DAT_TYPE_7_11 /* 0x11 Could be boxes for event activation? */,
    DAT_TYPE_0_TIE_INTERCEPTOR /* 0x12 */,
    DAT_TYPE_0_TIE_BOMBER /* 0x13 */,
    DAT_TYPE_0_GENERIC_BUILDING /* 0x14 These trigger the loading of the "destroyed building" model */,
    DAT_UNKNOWN_15 /* 0x15 */,
    DAT_TYPE_6_16 /* 0x16 */,
    DAT_TYPE_7_17 /* 0x17 Could be spheres for event activation? */,
    DAT_TYPE_7_18 /* 0x18 Could be timers for event activation? */,
    DAT_TYPE_7_19 /* 0x19 ?? */,
    DAT_TYPE_7_1A /* 0x1A One of the NONAME entry types */,
    DAT_TYPE_7_1B /* 0x1B One of the NONAME entry types */,
    DAT_TYPE_7_1C /* 0x1B One of the NONAME entry types */,
    DAT_UNKNOWN_1D /* 0x1D */,
    DAT_TYPE_0_MISSLE_TURRET /* 0x1E */,
    DAT_TYPE_0_ATST /* 0x1F */,
    DAT_TYPE_7_20 /* 0x1B One of the NONAME entry types */,
    DAT_TYPE_0_21 /* 0x21 Stationary NPC spawn locations? */,
    DAT_TYPE_7_22 /* 0x22 One of the NONAME entry types */,
    DAT_TYPE_7_23 /* 0x23 One of the NONAME entry types */,
    DAT_TYPE_0_SHUTTLE /* 0x24 */,
    DAT_TYPE_0_TANK_DROID /* 0x25 */,
    DAT_TYPE_0_CAMERA_POSITION /* 0x26 */,
    DAT_TYPE_0_WINGMAN_POSITION /* 0x27 Has a sub-sub-type to indicate the exact craft to be used */,
    /*
    This is really 3 models under one sub-type:
    The Gerrard V mega turrets
    The Trench Run mega turrets
    The generic mega turrets

    The exact model chosen is decided by the currently loaded level
    */
    DAT_TYPE_0_MEGA_TURRENT /* 0x28 */,
    DAT_TYPE_0_TIE_D /* 0x29 ?????? */,
    DAT_TYPE_0_RADAR_DISH /* 0x2A */,
    DAT_TYPE_0_REBEL_TRANSPORT /* 0x2B */,
    DAT_TYPE_0_HEAVY_SHUTTLE /* 0x2C */,
    DAT_TYPE_0_CARGO_01 /* 0x2D */,
    DAT_TYPE_0_REBEL_COMBAT /* 0x2E Don't know exactly what this is... */,
    // All three of these load the same model, I'm not sure why they're separate sub-types
    DAT_TYPE_0_IMPERIAL_TRAIN0 /* 0x2F */,
    DAT_TYPE_0_IMPERIAL_TRAIN1 /* 0x30 */,
    DAT_TYPE_0_IMPERIAL_TRAIN2 /* 0x31 */,
    DAT_TYPE_0_SHIELD /* 0x32 ????? */,
    DAT_TYPE_0_IMPERIAL_TRAIN_PILLAR /* 0x33 */,
    // Both of these load the same model, I'm not sure why they're separate sub-types
    DAT_TYPE_0_REBEL_TRAIN0 /* 0x34 */,
    DAT_TYPE_0_REBEL_TRAIN1 /* 0x35 */,
    DAT_TYPE_0_REBEL_TRAIN_PILLAR /* 0x36 */,
    DAT_TYPE_0_WORLD_DEVASTATOR /* 0x37 */,
    DAT_UNKNOWN_38 /* 0x38 */,
    DAT_TYPE_6_39 /* 0x39 One of the NONAME entry types */,
    DAT_TYPE_7_3A /* 0x3A One of the NONAME entry types */,
    DAT_TYPE_0_IMPERIAL_TROOPER /* 0x3B */,
    DAT_TYPE_0_REBEL_PILOT /* 0x3C */,
    DAT_TYPE_0_CIVILIAN /* 0x3D */,
    DAT_TYPE_0_ASSAULT_BOAT /* 0x3E */,
    DAT_UNKNOWN_3F /* 0x3F */,
    DAT_TYPE_0_WAVE_SKIMMER /* 0x40 */,
    DAT_TYPE_0_REBEL_TURRET /* 0x41 */,
    DAT_TYPE_0_TALORAAN_TURRET /* 0x42 */,
    DAT_TYPE_0_CLOUD_CAR /* 0x43 */,
    DAT_TYPE_0_IMPERIAL_PLATFORM /* 0x44 Not sure what exactly this is, maybe the floating platforms in the Taloraan level */,
    DAT_UNKNOWN_45 /* 0x45 */,
    DAT_TYPE_0_46 /* 0x46 Moving NPC spawn position? */,
    DAT_TYPE_0_ATPT /* 0x47 */,
    DAT_TYPE_0_BOSS_HUT /* 0x48 Only shows up once, named "MOFF SEERDON" */,
    DAT_TYPE_0_WORLD_DEVASTATOR_GUN /* 0x49 */,
    DAT_TYPE_0_POWER_GENERATOR /* 0x4A */,
    DAT_TYPE_0_4B /* 0x4B Large generic buildings? */,
    DAT_TYPE_0_POWER_UP /* 0x4C */,
    DAT_TYPE_0_HEAVY_RAPTOR_SHUTTLE /* 0x4D */,
    DAT_TYPE_7_4E /* 0x4E One of the NONAME entry types */,
    DAT_TYPE_0_EXHAUST_PORT /* 0x4F Death Star exhaust port */,
    DAT_TYPE_0_B_SOLDIER /* 0x50 Not present in any DAT files */,
    DAT_TYPE_2_LAVA_FARTS /* 0x51 Only used by the Raid on Sullust level */,
    DAT_TYPE_0_52 /* 0x52 One of the NONAME entry types */,
    DAT_NUM_SUBTYPES /* 0x53 */,
};

#endif
