#ifndef SECONDARY_WEAPONS_H
#define SECONDARY_WEAPONS_H

enum SecondaryWeapon {
    /* 0x00 */ SECONDARY_WEAPON_UNUSED, // not sure what's up with this...
    /* 0x01 */ SECONDARY_WEAPON_ION_CANNON,
    /* 0x02 */ SECONDARY_WEAPON_MISSLES,
    /* 0x03 */ SECONDARY_WEAPON_SEEKER_MISSILES,
    /* 0x04 */ SECONDARY_WEAPON_BOMBS,
    /* 0x05 */ SECONDARY_WEAPON_PROTON_TORPEDOS,
    /* 0x06 */ SECONDARY_WEAPON_TOW_CABLE,
    /* 0x07 */ SECONDARY_WEAPON_CLUSTER_MISSILES,
    /* 0x08 */ SECONDARY_WEAPON_SEEKER_TORPEDOS,
    /* 0x09 */ SECONDARY_WEAPON_SEEKER_CLUSTER_MISSILES,
    /* 0xFF */ SECONDARY_WEAPON_NONE = 0xFF,
};

enum SecondaryWeaponType {
    /* 0x0 */ SECONDARY_WEAPON_TYPE_MISSLE,
    /* 0x1 */ SECONDARY_WEAPON_TYPE_CLUSTER_MISSLE,
    /* 0x2 */ SECONDARY_WEAPON_TYPE_TORPEDO,
    /* 0x3 */ SECONDARY_WEAPON_TYPE_BOMB,
};

enum SecondaryWeaponLevel {
    /* 0x0 */ SECONDARY_WEAPON_LEVEL_NORMAL,
    /* 0x1 */ SECONDARY_WEAPON_LEVEL_ADVANCED,
    /* 0x2 */ SECONDARY_WEAPON_LEVEL_SEEKER,
};

#endif
